import fs from 'node:fs';
import path from 'node:path';
import { DB_FILE, VIDEOS_DIR, THUMBS_DIR } from './config.js';

/**
 * Seed the catalog with a few short demo clips on first run, so the UI
 * looks alive even before you upload your own movies.
 *
 * Sources are small public test clips (a few MB) that reliably allow
 * HTTP Range requests (needed for video seeking).
 */

const SAMPLES = [
  {
    id: 'demo-bbb',
    title: 'Big Buck Bunny — Test Clip',
    description: 'Short test clip used to demo the JaNixFlix player with seek/scrub support. Upload your own movies to replace it.',
    genre: 'Animation',
    year: 2008,
    duration: 10,
    videoFile: 'bbb.mp4',
    thumbnail: null, // auto-generated fallback thumbnail
    featured: true,
    rating: 8.0,
    source: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
  },
  {
    id: 'demo-bbb2',
    title: 'Big Buck Bunny — Clip 2',
    description: 'Another short test clip for the catalog. Delete it once you upload your own content.',
    genre: 'Animation',
    year: 2008,
    duration: 10,
    videoFile: 'bbb2.mp4',
    thumbnail: null,
    featured: false,
    rating: 7.5,
    source: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_2MB.mp4',
  },
];

export async function seedIfEmpty() {
  // Already seeded?
  if (fs.existsSync(DB_FILE)) {
    try {
      const existing = JSON.parse(fs.readFileSync(DB_FILE, 'utf-8') || '[]');
      if (existing.length > 0) return;
    } catch { /* corrupt — fall through and reseed */ }
  }

  console.log('[seed] First run — downloading demo clips...');
  const catalog = [];

  for (const s of SAMPLES) {
    try {
      await ensureSample(s);
      catalog.push({ ...s, source: undefined, createdAt: new Date().toISOString() });
      console.log(`[seed] ✓ ${s.title}`);
    } catch (err) {
      console.warn(`[seed] ✗ skipped ${s.title}: ${err.message}`);
    }
  }

  if (catalog.length) {
    fs.writeFileSync(DB_FILE, JSON.stringify(catalog, null, 2));
    console.log(`[seed] Catalog seeded with ${catalog.length} demo clips.`);
  } else {
    console.warn('[seed] No clips downloaded. Upload your own via POST /api/movies/upload.');
  }
}

async function ensureSample(sample) {
  const videoPath = path.join(VIDEOS_DIR, sample.videoFile);
  if (!fs.existsSync(videoPath)) {
    await download(sample.source, videoPath);
  }
  // Thumbnails are auto-generated by the server when missing — nothing to fetch.
}

async function download(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(dest, buf);
}
